export const ClassicalHall = [
    {
        id:1,
        mobiledeviceimage:"/assets/homepage/events/Events_375_Birthdays.jpg",
        mobwidth:425,
        mobheight:369,
        tabimage:"/assets/homepage/events/Events_Standard_Birthdays.jpg",
        tabwidth:768,
        tabheight:600,
        lagmobdevice :"/assets/homepage/events/Events_Standard_Birthdays.jpg",
        width:1280,
        height:1044,
        lgimage:"/assets/homepage/events/Events_1920_Birthdays.jpg",
        width:1920,
        height:1500,
        name:"Weddings"
    },
    {
        id:2,
        mobiledeviceimage:"/assets/homepage/events/Events_375_Birthdays.jpg",
        mobwidth:425,
        mobheight:369,
        tabimage:"/assets/homepage/events/Events_Standard_Birthdays.jpg",
        tabwidth:768,
        tabheight:600,
        lagmobdevice :"/assets/homepage/events/Events_Standard_Birthdays.jpg",
        width:1280,
        height:1044,
        lgimage:"/assets/homepage/events/Events_1920_Birthdays.jpg",
        width:1920,
        height:1500,
        name:"Birthday"
    },
    {
        id:3,
        mobiledeviceimage:"/assets/homepage/events/Events_375_Birthdays.jpg",
        mobwidth:425,
        mobheight:369,
        tabimage:"/assets/homepage/events/Events_Standard_Birthdays.jpg",
        tabwidth:768,
        tabheight:600,
        lagmobdevice :"/assets/homepage/events/Events_Standard_Birthdays.jpg",
        width:1280,
        height:1044,
        lgimage:"/assets/homepage/events/Events_1920_Birthdays.jpg",
        width:1920,
        height:1500,
        name:"Birthday"
    },
    {
        id:4,
        mobiledeviceimage:"/assets/homepage/events/Events_375_Birthdays.jpg",
        mobwidth:425,
        mobheight:369,
        tabimage:"/assets/homepage/events/Events_Standard_Birthdays.jpg",
        tabwidth:768,
        tabheight:600,
        lagmobdevice :"/assets/homepage/events/Events_Standard_Birthdays.jpg",
        width:1280,
        height:1044,
        lgimage:"/assets/homepage/events/Events_1920_Birthdays.jpg",
        width:1920,
        height:1500,
        name:"Birthday"
    },
    {
        id:5,
        mobiledeviceimage:"/assets/homepage/events/Events_375_Birthdays.jpg",
        mobwidth:425,
        mobheight:369,
        tabimage:"/assets/homepage/events/Events_Standard_Birthdays.jpg",
        tabwidth:768,
        tabheight:600,
        lagmobdevice :"/assets/homepage/events/Events_Standard_Birthdays.jpg",
        width:1280,
        height:1044,
        lgimage:"/assets/homepage/events/Events_1920_Birthdays.jpg",
        width:1920,
        height:1500,
        name:"Birthday"
    },

    
]
export const PremiumHall = [
    {
        id:1,
        mobiledeviceimage:"/assets/homepage/events/Events_375_Birthdays.jpg",
        mobwidth:425,
        mobheight:369,
        tabimage:"/assets/homepage/events/Events_Standard_Birthdays.jpg",
        tabwidth:768,
        tabheight:600,
        lagmobdevice :"/assets/homepage/events/Events_Standard_Birthdays.jpg",
        width:1280,
        height:1044,
        lgimage:"/assets/homepage/events/Events_1920_Birthdays.jpg",
        width:1920,
        height:1500,
        name:"Birthday"
    },
    {
        id:2,
        mobiledeviceimage:"/assets/homepage/events/Events_375_CorporateEvents.jpg",
        mobwidth:425,
        mobheight:369,
        tabimage:"/assets/homepage/events/Events_Standard_CorporateEvents.jpg",
        tabwidth:768,
        tabheight:600,
        lagmobdevice :"/assets/homepage/events/Events_Standard_CorporateEvents.jpg",
        width:1280,
        height:1044,
        lgimage:"/assets/homepage/events/Events_1920_CorporateEvents.jpg",
        width:1920,
        height:1500,
        name:"Corporate Events"
    },
    {
        id:3,
        mobiledeviceimage:"/assets/homepage/events/Events_375_OffsiteEvents.jpg",
        mobwidth:425,
        mobheight:369,
        tabimage:"/assets/homepage/events/Events_Standard_OffsiteEvents.jpg",
        tabwidth:768,
        tabheight:600,
        lagmobdevice :"/assets/homepage/events/Events_Standard_OffsiteEvents.jpg",
        width:1280,
        height:1044,
        lgimage:"/assets/homepage/events/Events_1920_OffsiteEvents.jpg",
        width:1920,
        height:1500,
        name:"Offsite Events"
    },
    {
        id:4,
        mobiledeviceimage:"/assets/homepage/events/Events_375_Weddings.jpg",
        mobwidth:425,
        mobheight:369,
        tabimage:"/assets/homepage/events/Events_Standard_Weddings.jpg",
        tabwidth:768,
        tabheight:600,
        lagmobdevice :"/assets/homepage/events/Events_Standard_Weddings.jpg",
        width:1280,
        height:1044,
        lgimage:"/assets/homepage/events/Events_1920_Weddings.jpg",
        width:1920,
        height:1500,
        name:"Weddings"
    },
 
]